# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='status1',
        ),
    ]
