# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170701_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status1',
            new_name='status',
        ),
    ]
